### ISSUE TITLE
Licensing information?

### ISSUE THREAD

**Issue by marvindanig** [mattdesl/tendril-webtoy-blog-post#1]
One usecase for this demo is to become a cover of a botany Superbook… but the licensing info isn't provided on repo. Can you clarify?

**Comment by mattdesl** [comment]
The demo source code is licensed under MIT – I added a [LICENSE.md](https://github.com/mattdesl/tendril-webtoy-blog-post/blob/master/demos/LICENSE.md) file.

The rest of the images/text in this blog post, and the actual Tendril web toy, do not fall under this license.

If you'd like a cover for a book I'd be happy to work with you, please drop me a line in my email. You can find my contact details on my [website](https://www.mattdesl.com/).

(I don't generally post my email in comments due to spam.)
